components:
  schemas:
    response.ErrorResponse:
      properties:
        code:
          example: 400
          type: integer
        msg:
          example: Bad Request
          type: string
      type: object
    route.CoursePointResponse:
      properties:
        bearing_after:
          type: integer
        bearing_before:
          type: integer
        cum_dist_m:
          type: number
        duration:
          type: number
        id:
          type: string
        instruction:
          type: string
        location:
          type: string
        maneuver_type:
          type: string
        modifier:
          type: string
        road_name:
          type: string
        seg_dist_m:
          type: number
        step_order:
          type: integer
      type: object
    route.CreateRouteRequest:
      type: object
    route.RouteListResponse:
      properties:
        routes:
          items:
            $ref: '#/components/schemas/route.RouteResponseModel'
          type: array
          uniqueItems: false
      type: object
    route.RouteResponse:
      properties:
        route:
          $ref: '#/components/schemas/route.RouteResponseModel'
      type: object
    route.RouteResponseModel:
      properties:
        bbox:
          type: string
        course_points:
          items:
            $ref: '#/components/schemas/route.CoursePointResponse'
          type: array
          uniqueItems: false
        created_at:
          type: string
        description:
          type: string
        distance:
          type: number
        duration:
          type: integer
        elevation_gain:
          type: number
        elevation_loss:
          type: number
        first_point:
          type: string
        highlighted_photo_id:
          type: integer
        id:
          type: string
        last_point:
          type: string
        name:
          type: string
        path_geom:
          type: string
        updated_at:
          type: string
        user_id:
          type: string
        user_name:
          type: string
        visibility:
          type: integer
        waypoints:
          items:
            $ref: '#/components/schemas/route.WaypointResponse'
          type: array
          uniqueItems: false
      type: object
    route.UpdateRouteRequest:
      type: object
    route.WaypointResponse:
      properties:
        id:
          type: string
        location:
          type: string
      type: object
    user.CreateUserRequest:
      properties:
        email:
          type: string
        first_name:
          type: string
        kratos_id:
          type: string
        last_name:
          type: string
        name:
          type: string
      required:
      - kratos_id
      - name
      type: object
    user.UserResponse:
      properties:
        user:
          $ref: '#/components/schemas/user.UserResponseModel'
      type: object
    user.UserResponseModel:
      properties:
        administrative_area:
          type: string
        country_code:
          type: string
        description:
          type: string
        email:
          type: string
        first_name:
          type: string
        geom:
          type: string
        has_set_location:
          type: boolean
        highlighted_photo_id:
          type: integer
        id:
          type: string
        last_name:
          type: string
        locale:
          type: string
        locality:
          type: string
        name:
          type: string
        postal_code:
          type: string
      type: object
  securitySchemes:
    CookieAuth:
      in: cookie
      name: ory_kratos_session
      type: apiKey
externalDocs:
  description: ""
  url: ""
info:
  description: This is a server for Cycle-Route API.
  title: Cycle-Route API
  version: "1.0"
openapi: 3.1.0
paths:
  /routes:
    post:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - type: object
              - $ref: '#/components/schemas/route.CreateRouteRequest'
                description: Create Route Request
                summary: request
        description: Create Route Request
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/route.RouteResponse'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Internal Server Error
      security:
      - CookieAuth: []
      summary: ルートを作成する
      tags:
      - routes
  /routes/{route_id}:
    delete:
      parameters:
      - description: Route ID
        in: path
        name: route_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Internal Server Error
      security:
      - CookieAuth: []
      summary: ルートを削除する
      tags:
      - routes
    get:
      parameters:
      - description: Route ID
        in: path
        name: route_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/route.RouteResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Internal Server Error
      summary: ルートを取得する
      tags:
      - routes
    put:
      parameters:
      - description: Route ID
        in: path
        name: route_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - type: object
              - $ref: '#/components/schemas/route.UpdateRouteRequest'
                description: Update Route Request
                summary: request
        description: Update Route Request
        required: true
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Internal Server Error
      security:
      - CookieAuth: []
      summary: ルートを更新する
      tags:
      - routes
  /users:
    post:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - type: object
              - $ref: '#/components/schemas/user.CreateUserRequest'
                description: Create User Request
                summary: request
        description: Create User Request
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user.UserResponse'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Internal Server Error
      summary: ユーザーを作成する
      tags:
      - users
  /users/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user.UserResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Internal Server Error
      security:
      - CookieAuth: []
      summary: ユーザーを取得する
      tags:
      - users
  /users/{user_id}/routes:
    get:
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/route.RouteListResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.ErrorResponse'
          description: Internal Server Error
      summary: ユーザーのルート一覧を取得する
      tags:
      - routes
servers:
- url: localhost:8080/api/v1
