name: Test
on:
  pull_request: # プルリクエストが作成されたら起動
    paths: # 変更されたファイルが以下のパターンにマッチする場合にのみ実行
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # ステップ1: チェックアウト
      - name: Set up Go
        uses: actions/setup-go@v5 # ステップ2: 言語セットアップ
        with:
          go-version-file: go.mod
      - run: go test ./... # ステップ3: テストの実行
